#!/usr/bin/env python
# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.4.1 on Sun Aug 05 14:39:56 2007

import wx

class MyMenuBar1(wx.MenuBar):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyMenuBar1.__init__
        wx.MenuBar.__init__(self, *args, **kwds)
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(File_Item, "Exit", "", wx.ITEM_NORMAL)
        self.Append(wxglade_tmp_menu, "File")
        wxglade_tmp_menu = wx.Menu()
        self.Append(wxglade_tmp_menu, "Help")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyMenuBar1.__set_properties
        pass
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyMenuBar1.__do_layout
        pass
        # end wxGlade

# end of class MyMenuBar1


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.Tile_text = wx.StaticText(self, -1, "Title")
        self.Title_textbox = wx.TextCtrl(self, -1, "")
        self.STime_text = wx.StaticText(self, -1, "Start Time")
        self.combo_box_1 = wx.ComboBox(self, -1, choices=[""], style=wx.CB_DROPDOWN)
        self.Duration_text = wx.StaticText(self, -1, "Duration")
        self.Duration_ctrl = wx.SpinCtrl(self, -1, "0", min=0, max=100)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("frame_1")
        self.Tile_text.SetMinSize((89, 12))
        self.Title_textbox.SetMinSize((200, -1))
        self.STime_text.SetMinSize((89, 13))
        self.combo_box_1.SetSelection(-1)
        self.Duration_text.SetMinSize((89, 13))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        time_slider = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4.Add(self.Tile_text, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_4.Add(self.Title_textbox, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_3.Add(sizer_4, 1, wx.EXPAND, 0)
        time_slider.Add(self.STime_text, 0, wx.ADJUST_MINSIZE, 0)
        time_slider.Add(self.combo_box_1, 0, wx.ADJUST_MINSIZE, 0)
        time_slider.Add(self.Duration_text, 0, wx.ADJUST_MINSIZE, 0)
        time_slider.Add(self.Duration_ctrl, 0, wx.ADJUST_MINSIZE, 0)
        sizer_3.Add(time_slider, 1, wx.EXPAND, 0)
        self.SetAutoLayout(True)
        self.SetSizer(sizer_3)
        sizer_3.Fit(self)
        sizer_3.SetSizeHints(self)
        self.Layout()
        # end wxGlade

# end of class MyFrame


